### ISSUE TITLE
UnboundLocalError: local variable 'uc' referenced before assignment

### ISSUE THREAD

**Issue by datafux** [scjurgen/pyfeld#2]
Hi,
I get the following error with allmost every command.

`pyfeld browse "0/My Music/Artists/Moby/Moby+Hotel"
- 0/My Music/Artists/Moby/Moby+Hotel/4393fe69e03c63583cc01857e32fd8ef \* Hotel Intro
- 0/My Music/Artists/Moby/Moby+Hotel/ba8336ed46cbf265a388a6e4ae0b0e89 \* Raining Again
- 0/My Music/Artists/Moby/Moby+Hotel/5806fcf236d882d545a6f7dfb44a6542 \* Beautiful
- 0/My Music/Artists/Moby/Moby+Hotel/a3fc17ebf2273681a0cb9876c9a74da5 \* Lift Me Up
- 0/My Music/Artists/Moby/Moby+Hotel/9a201eae35b6cd5312731fa9f0984859 \* Where You End
- 0/My Music/Artists/Moby/Moby+Hotel/df1a1599bf25485b1f3dbb11230f100d \* Temptation
- 0/My Music/Artists/Moby/Moby+Hotel/69ab12fdbcc7761ea0af752b67eb73e9 \* Spiders
- 0/My Music/Artists/Moby/Moby+Hotel/d49cf99511ee30a963385ddfe551ea45 \* Dream About Me
- 0/My Music/Artists/Moby/Moby+Hotel/61a95eab98b817b952a511a4359758cb \* Very
- 0/My Music/Artists/Moby/Moby+Hotel/7b72fd310e647ccadd6b5a6ed3530062 \* I Like It
- 0/My Music/Artists/Moby/Moby+Hotel/ae946851468d1d849f47ead162b75c7d \* Love Should
- 0/My Music/Artists/Moby/Moby+Hotel/97dd98fcb394e7be0d49fa5a0818186c \* Slipping Away
- 0/My Music/Artists/Moby/Moby+Hotel/3175b354c3f863a45cec482a3f123b51 \* Forever
- 0/My Music/Artists/Moby/Moby+Hotel/c48c780ea81f0808b8161292714e016e \* Homeward Angel
- 0/My Music/Artists/Moby/Moby+Hotel/54e74a19fa1fce236c9f458e5152766c \* 35 Minutes

pyfeld play "0/My Music/Artists/Moby/Moby+Hotel"

URI 0/My Music/Artists/Moby/Moby+Hotel dlna-playcontainer://uuid%3A68597541-193d-4975-9e66-75c9a17d2879?sid=urn%3Aupnp-org%3AserviceId%3AContentDirectory&cid=0/My%20Music/Artists/Moby/Moby%2BHotel&md=0
Traceback (most recent call last):
  File "/usr/local/bin/pyfeld", line 11, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.5/site-packages/pyfeld/rfcmd.py", line 681, in run_main
    uc.set_transport_uri(transport_data)
UnboundLocalError: local variable 'uc' referenced before assignment
`

**Comment by scjurgen** [comment]
Hi datafux,
Did you do a 
pyfeld -d info 
beforehand?It is needed to understand the infrasctructure (zones, rooms etc.)
If this doesn't help: How can I reproduce it? What is your infrastructure? Where is this music media playing from (Phone, USB key, samba share)?

Cheers,
Juergen

**Comment by datafux** [comment]
Hi Juergen,

I found the problem. I thought I can omit the zone and 0 will be set as default then.
pyfeld -z 0 play ... etc. solves it.

great tool! the ui looks promising and is defintely more user friendly than the command line.
do you have plans for an curses version? that would be my favorit.

Gruss Michael

**Comment by scjurgen** [comment]
Hi Michael,
are you german? If so we can talk also in german...
-z 0: This was a regression, I fixed it and will be in the next version.
curses: there is a preliminary skeleton accessible from the github repository (./browseRF.py). It will open a curses screen to select a song/folder.which then can be passed to the play command. Did not follow it much through as I did not need it for the moment. It is a nice to have as I also like the shell window for doing stuff. 
If you have other ideas you are very welcome to expose them ;-) 
CIao,Juergen

```
  From: datafux <notifications@github.com>
```

 To: scjurgen/pyfeld pyfeld@noreply.github.com 
Cc: Jürgen Schwietering scjurgen@yahoo.com; Comment comment@noreply.github.com
 Sent: Monday, October 17, 2016 11:50 PM
 Subject: Re: [scjurgen/pyfeld] UnboundLocalError: local variable 'uc' referenced before assignment (#2)

**Comment by datafux** [comment]
browseRF looks really nice. Browsing is fast but play doesnt work for me:

File "/usr/local/lib/python3.5/site-packages/pyfeld/browseRF.py", line 85, in play
    command = 'pyfeld --zonewithroom "' + self.play_in_room + '" play "' + path + '"'
TypeError: Can't convert 'bytes' object to str implicitly

Since I'm more of a hacker than a programmer I'm not able to fix. On the other hand this might be a good opportunity to learn python....

Do you work for teufel?
What would be nice is a mopidy plugin that would allow you to stream music from a rasperry to my raumfeld system. Do you know if this is technically feasible?
And yes I speak German but I think for the sake of global communication on github English might be the right choice ;-)

Gruss Michael

**Comment by scjurgen** [comment]
Hi Michael,

I fixed the issue at hand. Thanks for the effort to try it out ;)
If I have some time I will deepen the browseRF.py script. Some major stuff is missing there (scrolling, remember latest folder, select zones). Minor things like volume etc. will follow.

**Comment by datafux** [comment]
great! thanks.
